### ISSUE TITLE
Same type name in another module does not build

### ISSUE THREAD

**Issue by jtroeth1** [eProsima/Fast-DDS-python#105]
Hello,

I have a problem building some types where the name is the same, however the type lives in another module for example:
```c++
module module1
{
    struct Type1
    {
    };
};

module module2
{
    struct Type1
    {
    };
};
``` 

This will not build, with the error:
```
In file included from /home/user/software/Fast-DDS-python/fastdds_python_examples/bug/BugType.cxx:29:
/home/user/software/Fast-DDS-python/fastdds_python_examples/bug/BugType.h:89:29: error: ‘module1::Type1::Type1()’ cannot be overloaded with ‘module1::Type1::Type1()’
   89 |     eProsima_user_DllExport Type1();
      |                             ^~~~~
/home/user/software/Fast-DDS-python/fastdds_python_examples/bug/BugType.h:84:29: note: previous declaration ‘module1::Type1::Type1()’
   84 |     eProsima_user_DllExport Type1();
      |                             ^~~~~
/home/user/software/Fast-DDS-python/fastdds_python_examples/bug/BugType.h:156:29: error: ‘module2::Type1::Type1()’ cannot be overloaded with ‘module2::Type1::Type1()’
  156 |     eProsima_user_DllExport Type1();
``` 

Is this intended or should types be inside their respective namespace?

Thanks

**Comment by JesusPoderoso** [comment]
Hi @jtroeth1, thanks for using Fast DDS.
I am afraid that using namespaces is not supported in the Fast DDS python bindings.
The module's case has some limitations, such as the one you have experimented. You can actually use different module names, but the drawback is that you have to split them into separate idl files.
Sorry for the inconvenience, we will improve the documentation.

_idl_file1.idl_
```
module module1
{
    struct Type1
    {
    };
};
```
_idl_file_2.idl_
```
module module2
{
    struct Type1
    {
    };
};
```

**Comment by jtroeth1** [comment]
Actually @JesusPoderoso I don't think it does work having the files separate. I still get the same error.
