### ISSUE TITLE
 'HelloWorldPubSubType' object has no attribute 'setName'. Did you mean: 'set_name'?

### ISSUE THREAD

**Issue by SunLiangcan** [eProsima/Fast-DDS-python#182]
E:\test\build\Release>python HelloWorldExample.py -p publisher
Creating publisher.
Traceback (most recent call last):
  File "E:\test\build\Release\HelloWorldExample.py", line 206, in <module>
    writer = Writer(args.domain, args.machine)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\test\build\Release\HelloWorldExample.py", line 113, in __init__
    self.topic_data_type.setName("HelloWorldDataType")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HelloWorldPubSubType' object has no attribute 'setName'. Did you mean: 'set_name'?

**Comment by JesusPoderoso** [comment]
Hi @SunLiangcan, thanks for your report.
I am assuming you are using the Fast DDS python version from `master` branch.
Fast DDS, and Fast DDS Python, are near to a mayor release (v3.0.0 and v2.0.0, respectively). That entails several API breaks and refactors. For that reason, and until these versions are released, it is strongly advisable to use the latest stable branch, [2.14.x](https://github.com/eProsima/Fast-DDS/tree/2.14.x) (and python [v1.4.2](https://github.com/eProsima/Fast-DDS-python/tree/v1.4.2)).
It seems that performing the [`TopicDataType` refactor](https://github.com/eProsima/Fast-DDS/pull/5066) in the [python repository](https://github.com/eProsima/Fast-DDS-python/pull/165) we missed updating that example.
We will fix it and come back to you, sorry for the inconvenience.

**Comment by SunLiangcan** [comment]
ok,use 1.4.2 no problem

**Comment by JesusPoderoso** [comment]
Hi @SunLiangcan, we have already fixed it (#183) in `master`
