### ISSUE TITLE
Unable to run HelloWorldPublisher.py

### ISSUE THREAD

**Issue by Andrii-Rukhmakov** [eProsima/Fast-DDS-python#201]
Hi. I successfully  used this manual for creation of example of code.
https://fast-dds.docs.eprosima.com/en/latest/fastdds/getting_started/simple_python_app/simple_python_app.html
Each step was successfully passed, and as result I've got all necessary files for the project.
But when I try to run publisher or subscriber I always have tha same error:

andrii@jammy:~/workspace_HelloWorld$ python3 HelloWorldPublisher.py 
Traceback (most recent call last):
  File "/home/andrii/workspace_HelloWorld/HelloWorldPublisher.py", line 21, in <module>
    import HelloWorld
  File "/home/andrii/workspace_HelloWorld/HelloWorld.py", line 15, in <module>
    import _HelloWorldWrapper
ImportError: /home/andrii/workspace_HelloWorld/_HelloWorldWrapper.so: undefined symbol: _ZNK10HelloWorldeqERKS_

What I am doing wrong?

**Comment by Mario-DL** [comment]
Hi @Andrii-Rukhmakov,
I could not reproduce the issue, make sure you are using the latest `Fast DDS`, Fast DDS Gen v4.0.2](https://github.com/eProsima/Fast-DDS-Gen/releases/tag/v4.0.2) and sourcing the workspace before launching the script. I discovered an issue in the documentation regarding a couple of non-updated api calls in the Python examples and [opened this PR](https://github.com/eProsima/Fast-DDS-docs/pull/973).

**Comment by Andrii-Rukhmakov** [comment]
I used 2 different variants for build:
1.
For DDS lib -  sudo ./install.sh --no-static-libs --build-cores 24
source /home/andrii/colcon/fastdds_python_ws/install/setup.bash
fastddsgen -python HelloWorld.idl
cmake .
make

2. The same as first variant,  but  instead cmake and make I've used 
colcon build 
(result files were obtained from 'build' folder)

Also I've tried different variuants, like:
source /home/andrii/fastdds_python_ws/install/setup.bash
/home/andrii/fastdds_python_ws/src/fastddsgen/scripts/fastddsgen -python HelloWorld.idl
And each time I was unable to run demo..

On my screenshots below you can check the sequence of my steps:

![Screenshot_20241209_174903](https://github.com/user-attachments/assets/7aefdad0-7a17-426e-8f4b-c7756635d1c0)

![Screenshot_20241209_174926](https://github.com/user-attachments/assets/d22f5ace-6992-4660-840f-6f0adbc11926)

**Comment by Andrii-Rukhmakov** [comment]
Version of DDS is - eProsima_Fast-DDS-v2.14.2-Linux

**Comment by Mario-DL** [comment]
Using `SWIG` versions later than `4.1` is [not recommended](https://fast-dds.docs.eprosima.com/en/latest/installation/sources/sources_linux.html#swig). Please, check if using `SWIG 4.1` solves the issue. Also, for `Fast DDS 2.x versions` please use `Fast DDS Python 1.4.x` or the latest Fast DDS Python paired with the latest Fast DDS according to our [product compatibility matrix](https://fast-dds.docs.eprosima.com/en/latest/notes/versions.html)

**Comment by Andrii-Rukhmakov** [comment]
Hi Mario. Thank you for your clarification.
Now it works as expected. Looks like I had a complex issue. :)
I reinstalled swig and used new 3.1.0 version of Fast DDS and issue was fixed. Also I renamed 'getName' and 'setName' for class methods.

![Screenshot_20241210_110643](https://github.com/user-attachments/assets/34bc01da-9ca3-45f8-af3a-7a074bee0928)


Mario, possible it will be much better if for installation all the components will be provided more simple and detailed manual.

Just for example (simplest way):
1. Download Fast DDS from our Downloads page, unpack  and run sudo ./install.sh --no-static-libs --build-cores 24
2.  mkdir -p fastdds_python_ws/src
3. cd fastdds_python_ws
4. wget https://raw.githubusercontent.com/eProsima/Fast-DDS-python/main/fastdds_python.repos
5. vcs import src < fastdds_python.repos
6. Select necessary release version for each repo branch in 'src' according to https://fast-dds.docs.eprosima.com/en/latest/notes/versions.html 
7. colcon build
8. Run demo example (here also necessary fix for names of class methods).

It will save the time of your future customers :)))

**Comment by Mario-DL** [comment]
As part of the release procedure we test a basic backwards compatibility against all (active) supported versions. In general, fully compatibility is not guaranteed (except between different patch versions). Certain behavior changes or ABI breaks are expected across minor versions and API breaks across majors. One remarkable thing to mention between `3.x` and `2.x` is that the shared memory transport is not going to work as the segment file names have changed.
