### ISSUE TITLE
How to compile  Fast-DDS-python [14264]

### ISSUE THREAD

**Issue by YGD159** [eProsima/Fast-DDS-python#22]
I want to compile  Fast-DDS-python, it seems to have some problems.
I did the following these steps.
Ubuntu18.04
Swig 3.0.12
FastDDS 2.6

1. `pip3 install -U colcon-common-extensions vcstool`
2. `sudo apt update`
`sudo apt install -y \
    libasio-dev \
    libtinyxml2-dev`
`sudo apt install -y \
    swig \
    libpython3-dev`
3. `mkdir -p fastdds_python_ws/src`
`cd fastdds_python_ws`
`wget https://raw.githubusercontent.com/eProsima/Fast-DDS-python/main/fastdds_python.repos`
`vcs import src < fastdds_python.repos`
`colcon build`
![error](https://user-images.githubusercontent.com/52145923/160591816-6e1645f5-ddc6-40f3-a5c2-5f246b7eb3ba.png)

Can you give me some advice?
Yours support is greatly appreciated.

**Comment by JLBuenoLopez-eProsima** [comment]
Sorry, @YGD159,

[Fast DDS official support](https://github.com/eProsima/Fast-DDS/blob/master/PLATFORM_SUPPORT.md#platform-support) (and its related products) is for Ubuntu 20.04. Ubuntu 20.04 installs SWIG 4.0.1 by default. So I suppose there is some upgrade from SWIG 3.0.12 to 4.0.1 that prevents the Fast DDS Python bindings compilation. You may try installing manually a newer SWIG version in your Ubuntu 18.04 and try again.

**Comment by YGD159** [comment]
Thanks a lot for your suggestion, I will try it after a while




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "José Luis Bueno ***@***.***&gt;; 
发送时间: 2022年3月29日(星期二) 晚上7:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [eProsima/Fast-DDS-python] How to compile  Fast-DDS-python (Issue #22)





 
对不起，@ YGD159，
 
Fast DDS 官方支持（及其相关产品）适用于 Ubuntu 20.04。Ubuntu 20.04 默认安装 SWIG 4.0.1。所以我想从 SWIG 3.0.12 升级到 4.0.1 会阻止快速 DDS Python 绑定编译。您可以尝试在 Ubuntu 18.04 中手动安装更新的 SWIG 版本，然后重试。
 
—
直接回复此邮件，在 GitHub 上查看，或取消订阅。
你收到这个是因为你被提到了。Message ID: ***@***.***&gt;

**Comment by JLBuenoLopez-eProsima** [comment]
I will close the issue for the moment. If after trying with the supported version of SWIG you still have problems, feel free to reopen
