### ISSUE TITLE
Compilation error [14802]

### ISSUE THREAD

**Issue by 282902479** [eProsima/Fast-DDS-python#30]
当我使用colcon build编译fastdds_python时，报以下错误
When I compile fastdds using colcon build_ In Python, the following error is reported
----------------------------------------------------------------------------------------------------
/usr/share/swig3.0/std/std_vector.i:87: Error: Can't copy typemap (directorout) std::vector< eprosima::fastdds::dds::ViewStateKind,std::allocator< eprosima::fastdds::dds::ViewStateKind > > = std::vector< eprosima::fastdds::dds::ViewStateKind,std::allocator< eprosima::fastdds::dds::ViewStateKind > > &DIRECTOROUT
/usr/share/swig3.0/std/std_vector.i:87: Error: Can't copy typemap (in) std::vector< eprosima::fastdds::dds::ViewStateKind,std::allocator< eprosima::fastdds::dds::ViewStateKind > > *INPUT = std::vector< eprosima::fastdds::dds::ViewStateKind,std::allocator< eprosima::fastdds::dds::ViewStateKind > > *INOUT
/usr/share/swig3.0/std/std_vector.i:87: Error: Can't copy typemap (in) std::vector< eprosima::fastdds::dds::ViewStateKind,std::allocator< eprosima::fastdds::dds::ViewStateKind > > &INPUT = std::vector< eprosima::fastdds::dds::ViewStateKind,std::allocator< eprosima::fastdds::dds::ViewStateKind > > &INOUT
/usr/share/swig3.0/std/std_vector.i:87: Error: Can't copy typemap (typecheck) std::vector< eprosima::fastdds::dds::ViewStateKind,std::allocator< eprosima::fastdds::dds::ViewStateKind > > *INPUT = std::vector< eprosima::fastdds::dds::ViewStateKind,std::allocator< eprosima::fastdds::dds::ViewStateKind > > *INOUT
/usr/share/swig3.0/std/std_vector.i:87: Error: Can't copy typemap (typecheck) std::vector< eprosima::fastdds::dds::ViewStateKind,std::allocator< eprosima::fastdds::dds::ViewStateKind > > &INPUT = std::vector< eprosima::fastdds::dds::ViewStateKind,std::allocator< eprosima::fastdds::dds::ViewStateKind > > &INOUT
/usr/share/swig3.0/std/std_vector.i:87: Error: Can't copy typemap (argout) std::vector< eprosima::fastdds::dds::ViewStateKind,std::allocator< eprosima::fastdds::dds::ViewStateKind > > *OUTPUT = std::vector< eprosima::fastdds::dds::ViewStateKind,std::allocator< eprosima::fastdds::dds::ViewStateKind > > *INOUT
/usr/share/swig3.0/std/std_vector.i:87: Error: Can't copy typemap (argout) std::vector< eprosima::fastdds::dds::ViewStateKind,std::allocator< eprosima::fastdds::dds::ViewStateKind > > &OUTPUT = std::vector< eprosima::fastdds::dds::ViewStateKind,std::allocator< eprosima::fastdds::dds::ViewStateKind > > &INOUT
/usr/share/swig3.0/std/std_vector.i:87: Error: Can't copy typemap (typecheck) std::vector< eprosima::fastdds::dds::ViewStateKind,std::allocator< eprosima::fastdds::dds::ViewStateKind > > *INPUT = std::vector< eprosima::fastdds::dds::ViewStateKind,std::allocator< eprosima::fastdds::dds::ViewStateKind > > *INOUT
/usr/share/swig3.0/std/std_vector.i:87: Error: Can't copy typemap (typecheck) std::vector< eprosima::fastdds::dds::ViewStateKind,std::allocator< eprosima::fastdds::dds::ViewStateKind > > &INPUT = std::vector< eprosima::fastdds::dds::ViewStateKind,std::allocator< eprosima::fastdds::dds::ViewStateKind > > &INOUT

--------------------------------------------------------------------------------------------------------------
Please help me to solve this problem. Thank you very much

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @282902479,

Fast DDS Python bindings require SWIG version 4.0 in order to build. I have checked the documentation and it is true that this dependency requirement is not clearly stated. Sorry for the inconvenient! Please, upgrade your SWIG version and try again, and let me know if you have any other issue. I will leave this ticket open until a PR is merged stating the minimum required SWIG version to build the Python bindings.

Thanks for your contribution!
