### ISSUE TITLE
fastdds_python build failed

### ISSUE THREAD

**Issue by ytxloveyou** [eProsima/Fast-DDS-python#71]
Dear Support,

Just follow the official steps to install fastDDS_python, and i get below error:
inished <<< fastcdr [1.68s]
--- stderr: foonathan_memory_vendor                                
Cloning into 'foo_mem-ext'...
HEAD is now at 0f07757 Release 0.7-3
---
Finished <<< foonathan_memory_vendor [13.8s]
Starting >>> fastrtps
[Processing: fastrtps]                             
[Processing: fastrtps]                                      
Finished <<< fastrtps [1min 26s]                              
Starting >>> fastdds_python
--- stderr: fastdds_python               
                    
******/home/ytx/Desktop/TOPICS/fastdds_python_ws/install/fastcdr/include/fastcdr/xcdr/optional.hpp:129: Error: Syntax error - possibly a missing semicolon.**
make[2]: *** [src/swig/CMakeFiles/fastdds_python.dir/fastddsPYTHON.stamp] Error 1
make[2]: *** Deleting file 'src/swig/CMakeFiles/fastdds_python.dir/fastddsPYTHON.stamp'
make[1]: *** [src/swig/CMakeFiles/fastdds_python_swig_compilation.dir/all] Error 2
make: *** [all] Error 2
---**
Failed   <<< fastdds_python [0.79s, exited with code 2]**

Summary: 3 packages finished [1min 41s]
  1 package failed: fastdds_python
  3 packages had stderr output: fastcdr fastdds_python foonathan_memory_vendor
  1 package not processed

**Comment by ytxloveyou** [comment]
swig version is 4.0.2

**Comment by JLBuenoLopez-eProsima** [comment]
@ytxloveyou 

You must ensure that Fast CDR dependency is version 2.0.0. Otherwise you will get this error because Fast DDS Python increased to this major dependency in [version 1.3.0](https://github.com/eProsima/Fast-DDS-python/releases/tag/v1.3.0). Please, check the versions in your workspace and consider closing the issue.
