### ISSUE TITLE
Complex .idl struct using SHM when forcing UDPv4 Transport

### ISSUE THREAD

**Issue by andreclerigo** [eProsima/Fast-DDS-python#95]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

Publisher and Subscriber using UDPv4

### Current behavior

Publisher and Subscriber using SHM

### Steps to reproduce

file1.py
```python
import fastdds
from threading import Condition
import WarningPayload

class WriterListener (fastdds.DataWriterListener) :
    def __init__(self, writer) :
        self._writer = writer
        super().__init__()

    def on_publication_matched(self, datawriter, info) :
        if (0 < info.current_count_change) :
            print ("Publisher matched subscriber {}".format(info.last_subscription_handle))
            self._writer._cvDiscovery.acquire()
            self._writer._matched_reader += 1
            self._writer._cvDiscovery.notify()
            self._writer._cvDiscovery.release()
        else :
            print ("Publisher unmatched subscriber {}".format(info.last_subscription_handle))
            self._writer._cvDiscovery.acquire()
            self._writer._matched_reader += 1
            self._writer._cvDiscovery.notify()
            self._writer._cvDiscovery.release()

class Writer:
    def __init__(self):
        self._matched_reader = 0
        self._cvDiscovery = Condition()
        self.index = 0

        factory = fastdds.DomainParticipantFactory.get_instance()
        self.participant_qos = fastdds.DomainParticipantQos()
        factory.get_default_participant_qos(self.participant_qos)
        participant = factory.create_participant_with_profile('UDPParticipant')
        self.participant = participant

        self.topic_data_type = WarningPayload.WarningPayloadPubSubType()
        self.topic_data_type.setName("WarningPayload")
        self.type_support = fastdds.TypeSupport(self.topic_data_type)
        self.participant.register_type(self.type_support)

        self.topic_qos = fastdds.TopicQos()
        self.participant.get_default_topic_qos(self.topic_qos)
        self.topic = self.participant.create_topic("WarningPayloadTopic", self.topic_data_type.getName(), self.topic_qos)

        self.publisher_qos = fastdds.PublisherQos()
        self.participant.get_default_publisher_qos(self.publisher_qos)
        self.publisher = self.participant.create_publisher(self.publisher_qos)

        self.listener = WriterListener(self)
        self.writer_qos = fastdds.DataWriterQos()
        self.publisher.get_default_datawriter_qos(self.writer_qos)
        self.writer = self.publisher.create_datawriter(self.topic, self.writer_qos, self.listener)

    def write(self, data):
        self.writer.write(data)
        # debug some data info
        print(f"Writing WarningPayload")
        self.index = self.index + 1

    def wait_discovery(self):
        self._cvDiscovery.acquire()
        print ("Writer is waiting discovery...")
        self._cvDiscovery.wait_for(lambda : self._matched_reader != 0)
        self._cvDiscovery.release()
        print("Writer discovery finished...")

    def run(self):
        self.wait_discovery()
        print("Writer is running...")
        self.write(WarningPayload.WarningPayload())
        while True:
            passs
        self.delete()

if __name__ == "__main__":
    writer = Writer()
    writer.run()

```

file2.py
```python
import fastdds
import WarningPayload

class ReaderListener(fastdds.DataReaderListener):
    def __init__(self):
        super().__init__()
    
    def on_subscription_matched(self, datareader, info) :
        if (0 < info.current_count_change) :
            print ("Subscriber matched publisher {}".format(info.last_publication_handle))
        else :
            print ("Subscriber unmatched publisher {}".format(info.last_publication_handle))
    
    def on_data_available(self, reader):
        info = fastdds.SampleInfo()
        data = WarningPayload.WarningPayload()
        reader.take_next_sample(data, info)
        print(f"Received WarningPayload")

class Reader:
    def __init__(self):
        factory = fastdds.DomainParticipantFactory.get_instance()
        self.participant_qos = fastdds.DomainParticipantQos()
        factory.get_default_participant_qos(self.participant_qos)
        participant = factory.create_participant_with_profile('UDPParticipant')
        self.participant = participant

        self.topic_data_type = WarningPayload.WarningPayloadPubSubType()
        self.topic_data_type.setName("WarningPayload")
        self.type_support = fastdds.TypeSupport(self.topic_data_type)
        self.participant.register_type(self.type_support)

        self.topic_qos = fastdds.TopicQos()
        self.participant.get_default_topic_qos(self.topic_qos)
        self.topic = self.participant.create_topic("WarningPayloadTopic", self.topic_data_type.getName(), self.topic_qos)

        self.subscriber_qos = fastdds.SubscriberQos()
        self.participant.get_default_subscriber_qos(self.subscriber_qos)
        self.subscriber = self.participant.create_subscriber(self.subscriber_qos)

        self.listener = ReaderListener()
        self.reader_qos = fastdds.DataReaderQos()
        self.subscriber.get_default_datareader_qos(self.reader_qos)
        self.reader = self.subscriber.create_datareader(self.topic, self.reader_qos, self.listener)

    def run(self):
        print("Waiting for data...")
        while True:
            pass

reader = Reader()
reader.run()

while True:
    pass
```

python3 file1.py
python3 file2.py

### Fast DDS version/commit

https://github.com/eProsima/Fast-DDS-python main branch and latest commit

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

UDPv4, Shared Memory Transport (SHM)

### Additional context

Each participant (file1.py and file2.py) is running in a separate Docker container (using `--network host` but not `--ipc host`). The idea here is to force UDP communication, because sharing the namespace could result in security vulnerabilities. As for my understanding the XML file should disable SHM but the Writer is clearly trying to use it.

### XML configuration file

```xml
Using the following DEFAULT_FASTRTPS_PROFILES.xml file 


<?xml version="1.0" encoding="utf-8"  ?>
<profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
    <transport_descriptors>
        <!-- Create a descriptor for the new transport -->
        <transport_descriptor>
            <transport_id>udp_transport</transport_id>
            <type>UDPv4</type>
        </transport_descriptor>
    </transport_descriptors>

    <participant profile_name="UDPParticipant" is_default_profile="true">
        <rtps>
            <!--
                As customized versions of the default transports are used, the
                built-in ones should be disabled
            -->
            <useBuiltinTransports>false</useBuiltinTransports>
            <!-- Link the Transport Layer to the Participant -->
            <userTransports>
                <transport_id>udp_transport</transport_id>
            </userTransports>
        </rtps>
    </participant>
</profiles>
```

Using the following .idl struct
```c
struct Vehicle {
    long causeCode;
    long subCauseCodeVehicle;
    long vru_stationID;
    long sequenceNumber;
    sequence<double, 2> location;
    double altitude;
    double distance;
    double time;
};

struct VRU {
    long causeCode;
    long subCauseCodeVRU;
    long vehicle_stationID;
    long sequenceNumber;
    sequence<double, 2> location;
    double altitude;
    double distance;
    double time;
};

struct WarningPayload {
    double generationDeltaTime;
    VRU vruData;
    Vehicle vehicleData;
};
```
**NOTE:** Using a more simple .idl struct resolves the issue (that is, struct WarningPayload does not use other structs and only uses builtin datatypes like string, long, etc)

### Relevant log output

```shell
root@container:~/app# python3 file1.py 
Writer is waiting discovery...
2024-02-03 17:02:16.696 [HISTORY_DATASHARING_LISTENER Error] Failed to open segment fast_datasharing_01.0f.16.0e.39.05.5b.0d.00.00.00.00_0.0.1.4: No such file or directory -> Function open_and_init_shared_segment_notification
Publisher matched subscriber 1.f.16.e.39.5.5b.d.0.0.0.0.0.0.1.4
Writer discovery finished...
Writer is running...
Writing WarningPayload
```

```shell
root@container:~/app# python3 file2.py 
Waiting for data...
2024-02-03 17:02:16.695 [HISTORY_DATASHARING_PAYLOADPOOL Error] Failed to open segment fast_datasharing_01.0f.16.0e.61.08.c9.7f.00.00.00.00_0.0.1.3: No such file or directory -> Function init_shared_segment
2024-02-03 17:02:16.696 [RTPS_READER Error] Failed to add Writer Proxy 01.0f.16.0e.61.08.c9.7f.00.00.00.00|0.0.1.3 to 0.0.1.4 with data sharing. -> Function matched_writer_add
```

### Network traffic capture
No response

**Comment by JesusPoderoso** [comment]
Hi @andreclerigo, thanks for using Fast DDS.

Based on the log output, I don't think that your application is still trying to communicate through SHM. In this case, the communication might have been performed through [data-sharing transport](https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/datasharing.html) instead of UDP. 

> **NOTE**: Using a more simple .idl struct resolves the issue (that is, struct WarningPayload does not use other structs and only uses builtin datatypes like string, long, etc)

Did you make sure by using Wireshark or any other traffic analyzer that the communication in your described simple .idl struct was performed through UDP?

We've seen that Docker does not isolate the containers as expected, and the data-sharing transport may be detected as a possible transport if the [data-sharing constraints](https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/datasharing.html#constraints) are met (as long as data-sharing is configured as `AUTO` by default, it may happen in the simple .idl scenario when types are bounded).

A direct solution is to **disable data-sharing** in your code:

```
# in the __init__ method of the Writer class:
self.publisher_qos.data_sharing().off()
```

```
# in the __init__ method of the Reader class:
self.subscriber_qos.data_sharing().off()
```

**Comment by JesusPoderoso** [comment]
**TIP**: There is a new feature introduced in Fast DDS v2.13.0 that allows [configuring easily and faster the builtin transports](https://fast-dds.docs.eprosima.com/en/v2.13.1/fastdds/transport/tcp/tcp.html#configuration-of-builtin-transports).
Instead of **disabling builtin transport** and setting custom user transport, it allows configuring in one line (code or XML) [which builtin transport](https://fast-dds.docs.eprosima.com/en/v2.13.1/fastdds/env_vars/env_vars.html#fastdds-builtin-transports) do you want to use.

```
<!-before->
<?xml version="1.0" encoding="utf-8"  ?>
<profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
    <transport_descriptors>
        <transport_descriptor>
            <transport_id>udp_transport</transport_id>
            <type>UDPv4</type>
        </transport_descriptor>
    </transport_descriptors>

    <participant profile_name="UDPParticipant" is_default_profile="true">
        <rtps>
            <useBuiltinTransports>false</useBuiltinTransports>
            <userTransports>
                <transport_id>udp_transport</transport_id>
            </userTransports>
        </rtps>
    </participant>
</profiles>


<!-after v2.13.0->
<?xml version="1.0" encoding="utf-8"  ?>
<profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
    <participant profile_name="UDPParticipant" is_default_profile="true">
        <rtps>
            <builtinTransports>UDPv4</builtinTransports>
        </rtps>
    </participant>
</profiles>
```

```
// before
DomainParticipantQos qos;
auto udp_transport = std::make_shared<UDPv4TransportDescriptor>();
qos.transport().use_builtin_transports = false;
qos.transport().user_transports.push_back(udp_transport);

// after v2.13.0
DomainParticipantQos qos;
qos.setup_transports(eprosima::fastdds::rtps::BuiltinTransports::UDPv4);
```

**Comment by andreclerigo** [comment]
> **TIP**: There is a new feature introduced in Fast DDS v2.13.0 that allows [configuring easily and faster the builtin transports](https://fast-dds.docs.eprosima.com/en/v2.13.1/fastdds/transport/tcp/tcp.html#configuration-of-builtin-transports). Instead of **disabling builtin transport** and setting custom user transport, it allows configuring in one line (code or XML) [which builtin transport](https://fast-dds.docs.eprosima.com/en/v2.13.1/fastdds/env_vars/env_vars.html#fastdds-builtin-transports) do you want to use.
> 
> ```
> <!-before->
> <?xml version="1.0" encoding="utf-8"  ?>
> <profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
>     <transport_descriptors>
>         <transport_descriptor>
>             <transport_id>udp_transport</transport_id>
>             <type>UDPv4</type>
>         </transport_descriptor>
>     </transport_descriptors>
> 
>     <participant profile_name="UDPParticipant" is_default_profile="true">
>         <rtps>
>             <useBuiltinTransports>false</useBuiltinTransports>
>             <userTransports>
>                 <transport_id>udp_transport</transport_id>
>             </userTransports>
>         </rtps>
>     </participant>
> </profiles>
> 
> 
> <!-after v2.13.0->
> <?xml version="1.0" encoding="utf-8"  ?>
> <profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
>     <participant profile_name="UDPParticipant" is_default_profile="true">
>         <rtps>
>             <builtinTransports>UDPv4</builtinTransports>
>         </rtps>
>     </participant>
> </profiles>
> ```
> 
> ```
> // before
> DomainParticipantQos qos;
> auto udp_transport = std::make_shared<UDPv4TransportDescriptor>();
> qos.transport().use_builtin_transports = false;
> qos.transport().user_transports.push_back(udp_transport);
> 
> // after v2.13.0
> DomainParticipantQos qos;
> qos.setup_transports(eprosima::fastdds::rtps::BuiltinTransports::UDPv4);
> ```

Is this feature already out on the Docker Image `ubuntu-eprosima-dds-suite:v1.6.0`?

**Comment by JesusPoderoso** [comment]
> Is this feature already out on the Docker Image `ubuntu-eprosima-dds-suite:v1.6.0`?

Unfortunately not, it will be included soon in a new DDS Suite version.

**Comment by andreclerigo** [comment]
> > Is this feature already out on the Docker Image `ubuntu-eprosima-dds-suite:v1.6.0`?
> 
> Unfortunately not, it will be included soon in a new DDS Suite version.

On that note, is there a way to be notified or to monitor the new release of a new Docker DDS Suite Image?

**Comment by JesusPoderoso** [comment]
> > On that note, is there a way to be notified or to monitor the new release of a new Docker DDS Suite Image?
> 
> You can [star](https://docs.github.com/en/get-started/exploring-projects-on-github/saving-repositories-with-stars#starring-a-repository) the [DDS Suite](https://github.com/eProsima/DDS-Suite) repository so you would be notified (by email / GitHub notifications) when a new version is released.

Aso Watch > Custom > Releases in an option

**Comment by andreclerigo** [comment]
> Hi @andreclerigo, thanks for using Fast DDS.
> 
> Based on the log output, I don't think that your application is still trying to communicate through SHM. In this case, the communication might have been performed through [data-sharing](https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/datasharing.html) data transmission method instead of UDP transport.
> 
> > **NOTE**: Using a more simple .idl struct resolves the issue (that is, struct WarningPayload does not use other structs and only uses builtin datatypes like string, long, etc)
> 
> Did you make sure by using Wireshark or any other traffic analyzer that the communication in your described simple .idl struct was performed through UDP?
> 
> We've seen that Docker does not isolate the containers as expected, and the data-sharing may be detected as a possible data transmission method if the [data-sharing constraints](https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/datasharing.html#constraints) are met (as long as data-sharing is configured as `AUTO` by default, and the simple .idl scenario types can be bounded).
> 
> A direct solution is to **disable data-sharing** in your code:
> 
> ```
> # in the __init__ method of the Writer class:
> self.publisher_qos.data_sharing().off()
> ```
> 
> ```
> # in the __init__ method of the Reader class:
> self.subscriber_qos.data_sharing().off()
> ```

Is there something here that I am missing?

Code:
```python
class Reader:
    def __init__(self):
        factory = fastdds.DomainParticipantFactory.get_instance()
        self.participant_qos = fastdds.DomainParticipantQos()
        factory.get_default_participant_qos(self.participant_qos)
        participant = factory.create_participant_with_profile('UDPParticipant')
        self.participant = participant

        self.topic_data_type = WarningPayload.WarningPayloadPubSubType()
        self.topic_data_type.setName("WarningPayload")
        self.type_support = fastdds.TypeSupport(self.topic_data_type)
        self.participant.register_type(self.type_support)

        self.topic_qos = fastdds.TopicQos()
        self.participant.get_default_topic_qos(self.topic_qos)
        self.topic = self.participant.create_topic("WarningPayloadTopic", self.topic_data_type.getName(), self.topic_qos)

        self.subscriber_qos = fastdds.SubscriberQos()
        self.subscriber_qos.data_sharing().off()
        self.participant.get_default_subscriber_qos(self.subscriber_qos)
        self.subscriber = self.participant.create_subscriber(self.subscriber_qos)

        self.listener = ReaderListener()
        self.reader_qos = fastdds.DataReaderQos()
        self.subscriber.get_default_datareader_qos(self.reader_qos)
        self.reader = self.subscriber.create_datareader(self.topic, self.reader_qos, self.listener)
```

Output:
```bash
root@atcll-nos:~/app# python3 file2.py 
Traceback (most recent call last):
  File "/root/app/file2.py", line 52, in <module>
    reader = Reader()
  File "/root/app/file2.py", line 38, in __init__
    self.subscriber_qos.data_sharing().off()
AttributeError: 'SubscriberQos' object has no attribute 'data_sharing'
```

The same behaviour occurs on the Publisher.

**Comment by JesusPoderoso** [comment]
Yes!
It is not part of the participant QoS, it takes place in the Endpoints QoS:

> file1.py
> ```python
> class Writer:
>     def __init__(self):
>         self._matched_reader = 0
>         self._cvDiscovery = Condition()
>         self.index = 0
> 
>         factory = fastdds.DomainParticipantFactory.get_instance()
>         self.participant_qos = fastdds.DomainParticipantQos()
>         factory.get_default_participant_qos(self.participant_qos)
>         participant = factory.create_participant_with_profile('UDPParticipant')
>         self.participant = participant
> 
>         self.topic_data_type = WarningPayload.WarningPayloadPubSubType()
>         self.topic_data_type.setName("WarningPayload")
>         self.type_support = fastdds.TypeSupport(self.topic_data_type)
>         self.participant.register_type(self.type_support)
> 
>         self.topic_qos = fastdds.TopicQos()
>         self.participant.get_default_topic_qos(self.topic_qos)
>         self.topic = self.participant.create_topic("WarningPayloadTopic", self.topic_data_type.getName(), self.topic_qos)
> 
>         self.publisher_qos = fastdds.PublisherQos()
>         self.participant.get_default_publisher_qos(self.publisher_qos)
>         self.publisher = self.participant.create_publisher(self.publisher_qos)
> 
>         self.listener = WriterListener(self)
>         self.writer_qos = fastdds.DataWriterQos()
>         self.publisher.get_default_datawriter_qos(self.writer_qos)
>```

```
self.writer_qos.data_sharing().off()
```

>```python
>         self.writer = self.publisher.create_datawriter(self.topic, self.writer_qos, self.listener)
>
>    def write(self, data):
>         self.writer.write(data)
>         # debug some data info
>         print(f"Writing WarningPayload")
>         self.index = self.index + 1
> ```


> file2.py
> ```python
> class Reader:
>     def __init__(self):
>         factory = fastdds.DomainParticipantFactory.get_instance()
>         self.participant_qos = fastdds.DomainParticipantQos()
>         factory.get_default_participant_qos(self.participant_qos)
>         participant = factory.create_participant_with_profile('UDPParticipant')
>         self.participant = participant
> 
>         self.topic_data_type = WarningPayload.WarningPayloadPubSubType()
>         self.topic_data_type.setName("WarningPayload")
>         self.type_support = fastdds.TypeSupport(self.topic_data_type)
>         self.participant.register_type(self.type_support)
> 
>         self.topic_qos = fastdds.TopicQos()
>         self.participant.get_default_topic_qos(self.topic_qos)
>         self.topic = self.participant.create_topic("WarningPayloadTopic", self.topic_data_type.getName(), self.topic_qos)
> 
>         self.subscriber_qos = fastdds.SubscriberQos()
>         self.participant.get_default_subscriber_qos(self.subscriber_qos)
>         self.subscriber = self.participant.create_subscriber(self.subscriber_qos)
> 
>         self.listener = ReaderListener()
>         self.reader_qos = fastdds.DataReaderQos()
>         self.subscriber.get_default_datareader_qos(self.reader_qos)
>```


```
self.reader_qos.data_sharing().off()
```

>```python
>         self.reader = self.subscriber.create_datareader(self.topic, self.reader_qos, self.listener)
>
>    def run(self):
>         print("Waiting for data...")
>         while True:
>             pass
> ```

**Comment by JesusPoderoso** [comment]
@andreclerigo This is the [DDS Suite v1.7.0](https://github.com/eProsima/DDS-Suite/tree/eprosima-dds-suite-v1.7.0) which includes that builtin transport configuration in Fast DDS.

**Comment by andreclerigo** [comment]
> @andreclerigo This is the [DDS Suite v1.7.0](https://github.com/eProsima/DDS-Suite/tree/eprosima-dds-suite-v1.7.0) which includes that builtin transport configuration in Fast DDS.

@JesusPoderoso Since it isn't possible to create issues on https://github.com/eProsima/DDS-Suite/tree/eprosima-dds-suite-v1.7.0 I will address here the problems on migrating to dds-suit:v1.7.0.

```bash
docker load < ubuntu-eprosima-dds-suite\ v1.7.0.tar
docker run -it ubuntu-eprosima-dds-suite:v1.7.0
apt install apt install -y libasio-dev libtinyxml2-dev swig libpython3-dev cmake make vim
vim SimpleObjectInfo.idl
cmake .
make
```

SimpleObjectInfo.idl structure:
```c
struct SimpleObjectInfo
{
    string source;
    long stationID;
    double timestamp;
    double latitude;
    double longitude;
    sequence<double, 2> location;
    double altitude;
    double heading;
    double speed;
    double acceleration;
    double yaw_rate;
    double d_acceleration;
    double t_reaction;
    long weight;
    double length;
    double x;
    double y;
    double T4;
    double generationDeltaTime;
};
```

Output from make:
```bash
root@ac2adb77ed98:~# make
[ 16%] Building CXX object CMakeFiles/SimpleObjectInfo.dir/SimpleObjectInfo.cxx.o
In file included from /root/SimpleObjectInfo.cxx:29:
/root/SimpleObjectInfo.h:32:10: fatal error: fastcdr/cdr/fixed_size_string.hpp: No such file or directory
   32 | #include <fastcdr/cdr/fixed_size_string.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/SimpleObjectInfo.dir/build.make:76: CMakeFiles/SimpleObjectInfo.dir/SimpleObjectInfo.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:87: CMakeFiles/SimpleObjectInfo.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by andreclerigo** [comment]
Reopening the issue to continue discussing unrelated problems that cannot be migrated to the correct GitHub repository.
I will close the issue after the discussion is finished 😃

**Comment by JesusPoderoso** [comment]
Hi @andreclerigo, try to regenerate the types with [Fast DDS-Gen](https://github.com/eProsima/Fast-DDS-Gen)

**Comment by andreclerigo** [comment]
Got the same error, I've added a video following the steps described, maybe I am missing something here.

https://github.com/eProsima/Fast-DDS-python/assets/30603611/98cfb2dc-5a57-4aa6-bbc6-fc3827c7cca3
